dist: bionic

language: python

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install .

script: python tests/test_pyxdl.py
